### ISSUE TITLE
Cannot change Settings, issue with python?

### ISSUE THREAD

**Issue by isurus27** [nextgis/qgis.connect_points#2]
Hello,

I am running into an issue when I try to use the Connect Points plugin in QGIS (Mac) 2.18.2. Upon initial installation of the plugin I was able to adjust the Settings and execute the Connect Points function (which resulted in a python error) but now I cannot access the Settings to try and fix the issue. Instead, when I select 'Settings' I get the following error:

TypeError: cannot concatenate 'str' and 'QPyNullVariant' objects

2017-03-04T09:26:10	1	Traceback (most recent call last):
			  File "/Users/jeffkneebone/.qgis2/python/plugins/connect_points/plugin.py", line 104, in show   Settingsself._iface.mainWindow()
			  File "/Users/jeffkneebone/.qgis2/python/plugins/connect_points/dialog.py", line 171, in __init__curResultLayerName
			  File "/Users/jeffkneebone/.qgis2/python/plugins/connect_points/dialog.py", line 189, in fillControls
			QgisPlugin().plPrint("curResultLayerName: " + curResultLayerName)
			TypeError: cannot concatenate 'str' and 'QPyNullVariant' objects

I have tried re-installing the plugin several times (ensuring that the folder was deleted) and trashed the .qgis preferences (in User/Library/Preferences), however, the error persists, even when I open new projects.

I have some experience in programming but am not familiar with Python. Any help would be much appreciated!

Thanks,
-Jeff

**Comment by simgislab** [comment]
it seems like a bug, first run didn't produce a layer and now settings dialog crashes

@KolesovDmitry can you have a look?

**Comment by epapang** [comment]
Hi. I am having this same issue. Was this ever resolved?

**Comment by simgislab** [comment]
you can try new version
