### ISSUE TITLE
Feature Request: X, Y, Z Points

### ISSUE THREAD

**Issue by digitalbirth** [nextgis/qgis.connect_points#8]
I am using your plugin to join points but it would be great if the lines used the Z value (Elevation) of the points 

I am using this for a line of sight and have a high tower and lower features I'd like to connect.

Further to this, if the layer settings of the created line layer are displayed in 3d, it would be super helpful, for me and I'm sure others.

**Comment by ivanbarsukov** [comment]
Implemented in https://github.com/nextgis/qgis_connect_points/pull/10
